### ISSUE TITLE
qemu-alpine for Raspberry Pi 2

### ISSUE THREAD

**Issue by Piping** [tristanls/qemu-alpine#1]
Hi, 

Can you point out to me where should I modify your code to use the qemu source code from other place??

```bash
git clone https://github.com/0xabu/qemu.git -b raspi
git submodule update --init dtc
./configure
make -j$(nproc)
sudo make install
```

And I dont know how your patch files are generated?

**Comment by tristanls** [comment]
This is the portion of the Dockerfile that adds qemu GPG keys, downloads qemu, and extracts the `.tar.bz2` file: https://github.com/tristanls/qemu-alpine/blob/7c26484d12c4df0dc1de823ff2fa4d395aec441f/Dockerfile#L14-L20

It's been a while since I've worked on this. I'm pretty sure I manually created the edits and probably created the patch from a diff, something along the lines of: https://git-scm.com/docs/diff-generate-patch

**Comment by Piping** [comment]
Thank you!!
